-- ZA Pulse — Day 2B
-- Run this while connected to database: za_pulse
-- Creates empty dimension and lineage tables. Seed data is in 04_seed_dims_and_meta.sql.
-- Fact table is Day 5. Do not create it today.
--
-- PascalCase tables and columns are quoted on purpose.

DROP TABLE IF EXISTS meta."ManualObservation";
DROP TABLE IF EXISTS meta."LoadLog";
DROP TABLE IF EXISTS meta."Source";
DROP TABLE IF EXISTS core."DimEvent";
DROP TABLE IF EXISTS core."DimDate";
DROP TABLE IF EXISTS core."DimProvince";

DROP TABLE IF EXISTS meta.manual_observation;
DROP TABLE IF EXISTS meta.load_log;
DROP TABLE IF EXISTS meta.source;
DROP TABLE IF EXISTS core.dim_event;
DROP TABLE IF EXISTS core.dim_date;
DROP TABLE IF EXISTS core.dim_province;

CREATE TABLE core."DimProvince" (
    "ProvinceCode"  VARCHAR(10)  PRIMARY KEY,
    "ProvinceName"  TEXT         NOT NULL,
    "Population"    BIGINT,
    "RegionGroup"   TEXT,
    "IsNational"    BOOLEAN      NOT NULL DEFAULT FALSE
);

COMMENT ON TABLE core."DimProvince" IS
    'Conformed province dimension. Codes match the official CSV column names.';

CREATE TABLE core."DimDate" (
    "DateKey"       DATE         PRIMARY KEY,
    "YearNum"       INTEGER      NOT NULL,
    "QuarterNum"    INTEGER      NOT NULL,
    "MonthNum"      INTEGER      NOT NULL,
    "MonthName"     TEXT         NOT NULL,
    "WeekIso"       INTEGER      NOT NULL,
    "WeekdayNum"    INTEGER      NOT NULL,
    "WeekdayName"   TEXT         NOT NULL,
    "IsWeekend"     BOOLEAN      NOT NULL,
    "YearMonth"     TEXT         NOT NULL,
    "WaveName"      TEXT
);

COMMENT ON TABLE core."DimDate" IS
    'Calendar dimension for time intelligence. One row per day in the study window.';

CREATE TABLE core."DimEvent" (
    "EventId"         INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EventName"       TEXT         NOT NULL,
    "EventType"       TEXT         NOT NULL,
    "StartDate"       DATE         NOT NULL,
    "EndDate"         DATE,
    "DatePrecision"   TEXT         NOT NULL DEFAULT 'official',
    "Notes"           TEXT,
    "SourceNote"      TEXT,
    CONSTRAINT "DimEventTypeChk" CHECK ("EventType" IN ('lockdown', 'wave', 'milestone'))
);

COMMENT ON TABLE core."DimEvent" IS
    'Lockdown levels, named epidemic waves, and milestones used as dashboard bands.';

CREATE TABLE meta."Source" (
    "SourceId"      VARCHAR(16)  PRIMARY KEY,
    "SourceName"    TEXT         NOT NULL,
    "FileName"      TEXT,
    "SourceUrl"     TEXT,
    "Licence"       TEXT,
    "IngestMethod"  TEXT         NOT NULL,
    "TargetTable"   TEXT,
    "Notes"         TEXT
);

COMMENT ON TABLE meta."Source" IS
    'Catalogue of allowed inputs. If it is not listed here, it is not a source of truth.';

CREATE TABLE meta."LoadLog" (
    "LoadId"        INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceId"      VARCHAR(16)  REFERENCES meta."Source" ("SourceId"),
    "LoadedAt"      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    "LoadedBy"      TEXT         NOT NULL DEFAULT current_user,
    "RowCount"      INTEGER,
    "Status"        TEXT         NOT NULL,
    "Message"       TEXT,
    CONSTRAINT "LoadLogStatusChk" CHECK ("Status" IN ('started', 'success', 'fail'))
);

COMMENT ON TABLE meta."LoadLog" IS
    'Ingest history. Every COPY or notebook load should write a row here.';

CREATE TABLE meta."ManualObservation" (
    "ObsId"         INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ObsDate"       DATE         NOT NULL,
    "ProvinceCode"  VARCHAR(10)  REFERENCES core."DimProvince" ("ProvinceCode"),
    "Note"          TEXT         NOT NULL,
    "CreatedBy"     TEXT         NOT NULL,
    "CreatedAt"     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE meta."ManualObservation" IS
    'Analyst notes typed by hand. CreatedBy and CreatedAt are mandatory.';
